release v0.7.0 (#16)
* release v0.7.0

* update tests to fetch lando instead of building from source

* update tests to fetch lando instead of building from source part 2

Co-authored-by: Mike Pirog <mike@lando.dev>

diff --git a/.github/workflows/pr-python-tests.yml b/.github/workflows/pr-python-tests.yml
--- a/.github/workflows/pr-python-tests.yml
+++ b/.github/workflows/pr-python-tests.yml
@@ -9,6 +9,7 @@ jobs:
     env:
       TERM: xterm
     strategy:
+      fail-fast: false
       matrix:
         leia-tests:
           #- examples/2.x
@@ -21,22 +22,13 @@ jobs:
         node-version:
           - '16'
     steps:
-
       - name: Checkout code
         uses: actions/checkout@v2
       - name: Install node ${{ matrix.node-version }}
         uses: actions/setup-node@v2
         with:
           node-version: ${{ matrix.node-version }}
-      - name: Get Yarn cache directory
-        id: yarn-cache-dir-path
-        run: echo "::set-output name=dir::$(yarn cache dir)"
-      - name: Use Yarn cache
-        uses: actions/cache@v2
-        id: yarn-cache
-        with:
-          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
-          key: ${{ runner.os }}-yarn-${{ matrix.node-version }}-v6-${{ hashFiles('**/yarn.lock') }}
+          cache: yarn
       - name: Install Yarn dependencies
         run: yarn install --prefer-offline --frozen-lockfile
 
@@ -58,7 +50,7 @@ jobs:
       - name: Verify Lando works and we are dogfooding this plugin for tests
         run: |
           lando version
-          lando config --path plugins | grep python | grep /home/runner/work/python/python || echo "::error:: Not dogfooding this plugin correctly! "
+          lando config --path plugins | grep python | grep /home/runner/work/python/python || (echo "::error:: Not dogfooding this plugin correctly!" && exit 1)
 
       # This block should eventually become use lando/actions-leia@v2
       # @NOTE? Do we want a way for our leia-action to configure apparmor since
